#### **Numpy**

In [2]:
import numpy as np

In [3]:
ls = [1, 2, 3]
arr = np.array(ls)
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
ls = [[[1, 2, 3]]]
arr = np.array(ls)
type(arr)
arr.ndim

3

In [6]:
arr.size

3

In [7]:
arr.shape

(1, 1, 3)

In [9]:
np.array([12, 43, 25, 5.7])

array([12. , 43. , 25. ,  5.7])

In [10]:
np.array([12, 43, 25, 5.7, 7+9j])

array([12. +0.j, 43. +0.j, 25. +0.j,  5.7+0.j,  7. +9.j])

In [11]:
np.array([12, 43, 25, 5.7], dtype= 'int')

array([12, 43, 25,  5])

In [25]:
new_arr = np.array([[12, 43, 25],
                    [21, 57, 98],
                    [91, 55, 71]])
new_arr

array([[12, 43, 25],
       [21, 57, 98],
       [91, 55, 71]])

In [26]:
new_arr.ndim

2

In [27]:
np.array([[[[]]]]).ndim

4

In [28]:
np.array([[12, 43, 25],
                    [21, 57, 98],
                    [91, 55, np.nan]])

array([[12., 43., 25.],
       [21., 57., 98.],
       [91., 55., nan]])

In [29]:
np.array([[12, 43, 25],
                    [21, 57, 98],
                    [91, 55, None]])

array([[12, 43, 25],
       [21, 57, 98],
       [91, 55, None]], dtype=object)

In [32]:
list(range(1.5, 11.5))

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.arange(1.5, 11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [35]:
np.arange(1.5, 11.5, 2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
arr.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [47]:
arr = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.ones([2, 3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
np.ones([2, 3, 2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [54]:
np.ones([2, 3, 4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [55]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [56]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [57]:
np.full([2, 3], 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [58]:
np.full([2, 3], [7, 8, 9])

array([[7, 8, 9],
       [7, 8, 9]])

In [61]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.random.randint(1, 10, 5)

array([2, 2, 5, 7, 8], dtype=int32)

In [71]:
np.random.randint(1, 101)

65

In [76]:
np.random.randint(100, 200, [3, 4])

array([[158, 141, 148, 116],
       [123, 149, 147, 179],
       [121, 180, 178, 188]], dtype=int32)

In [77]:
np.random.rand(5)

array([0.19495518, 0.21293675, 0.99019146, 0.89446842, 0.20394568])

In [78]:
np.random.rand(1, 10, 5)

array([[[0.33976668, 0.96772814, 0.98992486, 0.33087263, 0.7583936 ],
        [0.87139613, 0.81028999, 0.43043022, 0.07851675, 0.51358991],
        [0.02920005, 0.5548149 , 0.28382902, 0.29229411, 0.69509142],
        [0.47557808, 0.82733411, 0.65983128, 0.96213922, 0.52783203],
        [0.71710755, 0.17422125, 0.22475318, 0.85459577, 0.43629029],
        [0.67519809, 0.81195255, 0.22065574, 0.97113509, 0.95035485],
        [0.197246  , 0.89910741, 0.43535247, 0.26570483, 0.43234374],
        [0.21611914, 0.50550857, 0.24721694, 0.45705715, 0.46833601],
        [0.43065697, 0.35117783, 0.57532078, 0.44835691, 0.50159158],
        [0.46051186, 0.37228359, 0.79859975, 0.0542506 , 0.32049675]]])

In [79]:
np.random.randn(5)

array([-1.34162381, -0.57040301,  0.81137389, -0.41762408,  0.47769835])

In [80]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [83]:
np.linspace(2, 5, retstep=True)

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [85]:
arr = np.arange(1, 11).reshape([2, 5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### **Copy And View**

In [86]:
new_arr = arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [87]:
arr[0][0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [88]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [89]:
new_arr_copy = arr.copy()
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [91]:
arr[0][0] = 1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [92]:
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [93]:
arr.transpose()

array([[1000,    6],
       [   2,    7],
       [   3,    8],
       [   4,    9],
       [   5,   10]])

In [94]:
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [95]:
new_arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [96]:
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])